version: '3.9'
services:
  koori_admin:
    build:
      context: ./koori_front
    volumes:
      - koori_front:/usr/src/koori_front
    ports:
      - "4200:4200"

  koori_backend:
    build:
      context: ./koori_backend
    volumes:
      - koori_backend:/usr/src/koori_backend
    ports:
      - "8001:3001"
    depends_on:
      - postgres_db

  postgres_db:
      image: postgres:15
      container_name: petaaw_postgres
      restart: always
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: petaaw
      volumes:
        - local-postgres:/var/lib/postgresql/data

  pgadmin:
      image: dpage/pgadmin4:6
      container_name: petaaw_pgadmin
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: root@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: root
      volumes:
        - local-pgadmin:/var/lib/pgadmin4/storage
      ports:
        - "5050:80"
      depends_on:
        - postgres_db

  # keycloak:
  #     image: jboss/keycloak
  #     environment:
  #       DB_VENDOR: POSTGRES
  #       DB_ADDR: postgres_db
  #       DB_DATABASE: root
  #       DB_USER: root
  #       DB_SCHEMA: public
  #       DB_PASSWORD: root
  #       KEYCLOAK_USER: admin
  #       KEYCLOAK_PASSWORD: admin
  #     ports:
  #       - 8080:8080
  #     depends_on:
  #       - postgres_db

volumes:
  local-postgres:
  local-pgadmin:
  koori_backend:

