version: '3.9'
services:
  koori_admin:
    # container_name: petaaw_frontend
    build:
      context: ./koori_front
    volumes:
      - ./koori_front:/usr/src/koori_front
    ports:
      - "4200:4200"


  # application node_app
  koori_backend:
    # container_name: koori_backend
    build:
      context: ./koori_backend
    volumes:
      - ./koori_backend:/usr/src/koori_backend
    ports:
      - "8001:3001"
    depends_on:
      - postgres_db

  postgres_db:
      # container_name: petaaw_postgres_db
      # hostname: postgres_db
      extra_hosts:
        - "host.docker.internal:host-gateway"
      image: postgres:15
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: petaaw
        # DATABASE_URL: postgres://root:root@db:5432/petaaw
      ports:
        - "5432:5432"
      restart: always
      volumes:
      # - database-data:/var/lib/postgresql/data/
      - ./Data/postgresDB:/var/lib/postgresql/data
      networks:
        koori_net:
          ipv4_address: 192.168.0.2
  pgadmin:
      # container_name: pgadmin_container
      hostname: pgAdmin
      image: dpage/pgadmin4:6
      environment:
        PGADMIN_DEFAULT_EMAIL: root@pgadmin.com
        PGADMIN_DEFAULT_PASSWORD: root
        # PGADMIN_CONFIG_SERVER_MODE: 'True'

      restart: always
      volumes:
        - ./Data/pgadmin:/var/lib/pgadmin4/storage


      ports:
        - "9090:80"
      depends_on:
        - postgres_db
      networks:
        koori_net:
          ipv4_address: 192.168.0.3



      #KeyCloack
  # keycloak:
  #     image: jboss/keycloak
  #     environment:
  #       DB_VENDOR: POSTGRES
  #       DB_ADDR: postgres_db
  #       DB_DATABASE: root
  #       DB_USER: root
  #       DB_SCHEMA: public
  #       DB_PASSWORD: root
  #       KEYCLOAK_USER: admin
  #       KEYCLOAK_PASSWORD: admin
  #     ports:
  #       - 8080:8080
  #     depends_on:
  #       - postgres_db


volumes:
  database-data:
  pgadmin-data:
  koori_backend:

networks:
  koori_net:
    ipam:
      driver: default
      config:
      - subnet: "192.168.0.0/24"
        gateway: 192.168.0.1
