module.exports = {
    profil: require('./profilValidation'),
    user: require('./userValidation'),
    contact: require('./contactValidation'),
    sujet: require('./sujetValidation'),
    etape: require('./etapesValidation'),
    commentaire: require('./CommentaireValidation'),
    session: require('./sessionValidation'),
    fiche: require('./ficheValidation'),
    koori: require('./kooriValidation'),
    service: require('./serviceValidation'),
    temoignage: require('./temoignageValidation'),
    evaluation_note: require('./evaluation_noteValidation'),
    evaluation_koori: require('./evaluation_kooriValidation'),
    evaluation_ibox: require('./evaluation_iboxValidation'),
    evaluation_fiche: require('./evaluation_ficheValidation'),
    demande: require('./demandeValidation'),
    rapport_phase: require('./rapport_phaseValidation'),
}